# Generated by Django 4.2.1 on 2025-10-15 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AjusteInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.CharField(max_length=120)),
                ('estado', models.CharField(default='OPEN', max_length=30)),
            ],
            options={
                'db_table': 'ajustes_inventario',
            },
        ),
        migrations.CreateModel(
            name='AreaBodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'areas_bodega',
            },
        ),
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('codigo', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'bodegas',
            },
        ),
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=150)),
                ('codigo', models.CharField(blank=True, max_length=50)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.categoriaproducto')),
            ],
            options={
                'db_table': 'categorias_productos',
            },
        ),
        migrations.CreateModel(
            name='DefinicionAtributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_dato', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'definiciones_atributos',
            },
        ),
        migrations.CreateModel(
            name='DevolucionProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='DRAFT', max_length=30)),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bodega')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones_recibidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'devoluciones_proveedor',
            },
        ),
        migrations.CreateModel(
            name='LoteProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_lote', models.CharField(max_length=100)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('fecha_fabricacion', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lotes_producto',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'marcas',
            },
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('numero_orden', models.CharField(max_length=60, unique=True)),
                ('estado', models.CharField(default='DRAFT', max_length=30)),
                ('fecha_esperada', models.DateField(blank=True, null=True)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bodega')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_compra_proveedor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ordenes_compra',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('es_serializado', models.BooleanField(default=False)),
                ('tiene_vencimiento', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.categoriaproducto')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.marca')),
            ],
            options={
                'db_table': 'productos',
            },
        ),
        migrations.CreateModel(
            name='ReglaAlerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('configuracion', models.JSONField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'reglas_alerta',
            },
        ),
        migrations.CreateModel(
            name='SerieProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(max_length=150)),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.loteproducto')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='core.producto')),
            ],
            options={
                'db_table': 'series_producto',
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('direccion', models.TextField(blank=True)),
                ('ciudad', models.CharField(blank=True, max_length=120)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('pais', models.CharField(default='Chile', max_length=120)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'sucursales',
            },
        ),
        migrations.CreateModel(
            name='TasaImpuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=100)),
                ('porcentaje', models.DecimalField(decimal_places=3, max_digits=6)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tasas_impuesto',
            },
        ),
        migrations.CreateModel(
            name='TipoMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.SmallIntegerField()),
                ('afecta_costo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tipos_movimiento',
            },
        ),
        migrations.CreateModel(
            name='TipoUbicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'tipos_ubicacion',
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'unidades_medida',
            },
        ),
        migrations.CreateModel(
            name='UsuarioPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('rut', models.CharField(blank=True, max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('BODEGUERO', 'Bodeguero'), ('AUDITOR', 'Auditor'), ('PROVEEDOR', 'Proveedor')], default='BODEGUERO', max_length=20)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usuarios_perfil',
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('codigo', models.CharField(max_length=60)),
                ('nombre', models.CharField(blank=True, max_length=150)),
                ('pickeable', models.BooleanField(default=True)),
                ('almacenable', models.BooleanField(default=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.areabodega')),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones', to='core.bodega')),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tipoubicacion')),
            ],
            options={
                'db_table': 'ubicaciones',
            },
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='DRAFT', max_length=30)),
                ('bodega_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_entrada', to='core.bodega')),
                ('bodega_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_salida', to='core.bodega')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transferencias',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_disponible', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('cantidad_reservada', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.loteproducto')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='core.producto')),
                ('serie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.serieproducto')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='core.ubicacion')),
            ],
            options={
                'db_table': 'stock',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cantidad_reservada', models.DecimalField(decimal_places=6, max_digits=20)),
                ('tabla_referencia', models.CharField(blank=True, max_length=100)),
                ('referencia_id', models.BigIntegerField(blank=True, null=True)),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.loteproducto')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
                ('serie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.serieproducto')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ubicacion')),
            ],
            options={
                'db_table': 'reservas',
            },
        ),
        migrations.CreateModel(
            name='RecuentoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('codigo_ciclo', models.CharField(blank=True, max_length=60)),
                ('estado', models.CharField(default='OPEN', max_length=30)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bodega')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recuentos_inventario',
            },
        ),
        migrations.CreateModel(
            name='RecepcionMercaderia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('numero_recepcion', models.CharField(max_length=60, unique=True)),
                ('estado', models.CharField(default='OPEN', max_length=30)),
                ('recibido_en', models.DateTimeField(auto_now_add=True)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bodega')),
                ('orden_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ordencompra')),
                ('recibido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recepciones_mercaderia',
            },
        ),
        migrations.CreateModel(
            name='ProductoUsuarioProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_proveedor', models.CharField(blank=True, max_length=100)),
                ('tiempo_entrega_dias', models.IntegerField(default=7)),
                ('cantidad_min_pedido', models.DecimalField(decimal_places=6, default=1, max_digits=20)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_proveedor', to='core.producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_suministrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'productos_usuarios_proveedor',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='tasa_impuesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tasaimpuesto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unidadmedida'),
        ),
        migrations.CreateModel(
            name='PrecioProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=4, max_digits=14)),
                ('vigente_desde', models.DateField(auto_now_add=True)),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='core.producto')),
            ],
            options={
                'db_table': 'precios_producto',
            },
        ),
        migrations.CreateModel(
            name='PoliticaReabastecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_min', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('cantidad_max', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('cantidad_reorden', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('dias_cobertura', models.IntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
                ('ubicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ubicacion')),
            ],
            options={
                'db_table': 'politicas_reabastecimiento',
            },
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='tasa_impuesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tasaimpuesto'),
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('titulo', models.CharField(max_length=200)),
                ('cuerpo', models.TextField(blank=True)),
                ('leida', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notificaciones',
            },
        ),
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=6, max_digits=20)),
                ('tabla_referencia', models.CharField(blank=True, max_length=100)),
                ('referencia_id', models.BigIntegerField(blank=True, null=True)),
                ('ocurrido_en', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.loteproducto')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
                ('serie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.serieproducto')),
                ('tipo_movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipomovimiento')),
                ('ubicacion_desde', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_desde', to='core.ubicacion')),
                ('ubicacion_hasta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_hasta', to='core.ubicacion')),
                ('unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.unidadmedida')),
            ],
            options={
                'db_table': 'movimientos_stock',
            },
        ),
        migrations.AddField(
            model_name='loteproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='core.producto'),
        ),
        migrations.CreateModel(
            name='LineaTransferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=6, max_digits=20)),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.loteproducto')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
                ('serie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.serieproducto')),
                ('transferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='core.transferencia')),
                ('unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.unidadmedida')),
            ],
            options={
                'db_table': 'lineas_transferencia',
            },
        ),
        migrations.CreateModel(
            name='LineaRecuentoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_sistema', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('cantidad_contada', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('diferencia', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('contado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.loteproducto')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
                ('recuento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='core.recuentoinventario')),
                ('serie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.serieproducto')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ubicacion')),
            ],
            options={
                'db_table': 'lineas_recuento_inventario',
            },
        ),
        migrations.CreateModel(
            name='LineaRecepcionMercaderia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_recibida', models.DecimalField(decimal_places=6, max_digits=20)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.loteproducto')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
                ('recepcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='core.recepcionmercaderia')),
                ('serie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.serieproducto')),
                ('unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.unidadmedida')),
            ],
            options={
                'db_table': 'lineas_recepcion_mercaderia',
            },
        ),
        migrations.CreateModel(
            name='LineaOrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True)),
                ('cantidad_pedida', models.DecimalField(decimal_places=6, max_digits=20)),
                ('precio', models.DecimalField(decimal_places=4, max_digits=14)),
                ('descuento_pct', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('orden_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='core.ordencompra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unidadmedida')),
            ],
            options={
                'db_table': 'lineas_orden_compra',
            },
        ),
        migrations.CreateModel(
            name='LineaDevolucionProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=6, max_digits=20)),
                ('devolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='core.devolucionproveedor')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.loteproducto')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
                ('serie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.serieproducto')),
                ('unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.unidadmedida')),
            ],
            options={
                'db_table': 'lineas_devolucion_proveedor',
            },
        ),
        migrations.CreateModel(
            name='LineaAjusteInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_delta', models.DecimalField(decimal_places=6, max_digits=20)),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('ajuste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='core.ajusteinventario')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.loteproducto')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
                ('serie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.serieproducto')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ubicacion')),
            ],
            options={
                'db_table': 'lineas_ajuste_inventario',
            },
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('texto_alternativo', models.CharField(blank=True, max_length=200)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='core.producto')),
            ],
            options={
                'db_table': 'imagenes_producto',
            },
        ),
        migrations.CreateModel(
            name='FacturaProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=80)),
                ('monto_total', models.DecimalField(decimal_places=4, max_digits=14)),
                ('fecha_factura', models.DateField()),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(default='OPEN', max_length=30)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas_emitidas', to=settings.AUTH_USER_MODEL)),
                ('tasa_impuesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tasaimpuesto')),
            ],
            options={
                'db_table': 'facturas_proveedor',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(max_length=60)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'documentos',
            },
        ),
        migrations.CreateModel(
            name='ConversionUM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.DecimalField(decimal_places=6, max_digits=20)),
                ('unidad_desde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversiones_desde', to='core.unidadmedida')),
                ('unidad_hasta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversiones_hasta', to='core.unidadmedida')),
            ],
            options={
                'db_table': 'conversiones_um',
            },
        ),
        migrations.AddField(
            model_name='bodega',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bodegas', to='core.sucursal'),
        ),
        migrations.CreateModel(
            name='BitacoraAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('accion', models.CharField(max_length=100)),
                ('tabla', models.CharField(blank=True, max_length=100)),
                ('entidad_id', models.BigIntegerField(blank=True, null=True)),
                ('detalle', models.JSONField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bitacora_auditoria',
            },
        ),
        migrations.CreateModel(
            name='AtributoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_texto', models.TextField(blank=True, null=True)),
                ('valor_numero', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('valor_booleano', models.BooleanField(blank=True, null=True)),
                ('valor_fecha', models.DateField(blank=True, null=True)),
                ('atributo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.definicionatributo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atributos', to='core.producto')),
            ],
            options={
                'db_table': 'atributos_producto',
            },
        ),
        migrations.AddField(
            model_name='areabodega',
            name='bodega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='core.bodega'),
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('severidad', models.CharField(default='INFO', max_length=20)),
                ('mensaje', models.TextField()),
                ('reconocida_en', models.DateTimeField(blank=True, null=True)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.producto')),
                ('reconocida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_reconocidas', to=settings.AUTH_USER_MODEL)),
                ('regla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.reglaalerta')),
                ('ubicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ubicacion')),
            ],
            options={
                'db_table': 'alertas',
            },
        ),
        migrations.AddField(
            model_name='ajusteinventario',
            name='bodega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bodega'),
        ),
        migrations.AddField(
            model_name='ajusteinventario',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Adjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('url_archivo', models.URLField()),
                ('nombre_archivo', models.CharField(blank=True, max_length=200)),
                ('tipo_contenido', models.CharField(blank=True, max_length=100)),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjuntos', to='core.documento')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjuntos', to='core.producto')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjuntos_usuario_proveedor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'adjuntos',
            },
        ),
        migrations.AddConstraint(
            model_name='ubicacion',
            constraint=models.UniqueConstraint(fields=('bodega', 'codigo'), name='uq_ubicacion_bodega_codigo'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['producto'], name='idx_stock_producto'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['ubicacion'], name='idx_stock_ubicacion'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.UniqueConstraint(fields=('producto', 'ubicacion', 'lote', 'serie'), name='uq_stock_prod_ubi_lote_serie'),
        ),
        migrations.AddConstraint(
            model_name='serieproducto',
            constraint=models.UniqueConstraint(fields=('producto', 'numero_serie'), name='uq_producto_numero_serie'),
        ),
        migrations.AddConstraint(
            model_name='productousuarioproveedor',
            constraint=models.UniqueConstraint(fields=('producto', 'proveedor'), name='uq_producto_usuario_proveedor'),
        ),
        migrations.AddConstraint(
            model_name='politicareabastecimiento',
            constraint=models.UniqueConstraint(fields=('producto', 'ubicacion'), name='uq_politica_reabastecimiento'),
        ),
        migrations.AddIndex(
            model_name='movimientostock',
            index=models.Index(fields=['producto', 'ocurrido_en'], name='idx_mov_stock_prod_fecha'),
        ),
        migrations.AddConstraint(
            model_name='loteproducto',
            constraint=models.UniqueConstraint(fields=('producto', 'codigo_lote'), name='uq_producto_lote'),
        ),
        migrations.AddConstraint(
            model_name='facturaproveedor',
            constraint=models.UniqueConstraint(fields=('proveedor', 'numero_factura'), name='uq_proveedor_numero_factura'),
        ),
        migrations.AddConstraint(
            model_name='conversionum',
            constraint=models.UniqueConstraint(fields=('unidad_desde', 'unidad_hasta'), name='uq_conversion_um'),
        ),
        migrations.AddConstraint(
            model_name='bodega',
            constraint=models.UniqueConstraint(fields=('sucursal', 'codigo'), name='uq_bodega_sucursal_codigo'),
        ),
        migrations.AddConstraint(
            model_name='atributoproducto',
            constraint=models.UniqueConstraint(fields=('producto', 'atributo'), name='uq_producto_atributo'),
        ),
        migrations.AddConstraint(
            model_name='areabodega',
            constraint=models.UniqueConstraint(fields=('bodega', 'codigo'), name='uq_area_bodega_codigo'),
        ),
    ]
