# Generated by Django 5.2.6 on 2025-11-25 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferencia',
            name='fecha_emision',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='numero_guia',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
