# Generated by Django 5.2.6 on 2025-11-25 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_transferencia_fecha_emision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferencia',
            name='bodega_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_destino', to='core.bodega'),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='sucursal_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_sucursal_destino', to='core.sucursal'),
        ),
    ]
