# Generated by Django 5.2.6 on 2025-11-25 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_transferencia_bodega_destino_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferencia',
            name='observaciones',
        ),
        migrations.AddField(
            model_name='transferencia',
            name='sucursal_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_sucursal_origen', to='core.sucursal'),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='tipo_movimiento',
            field=models.CharField(choices=[('BOD_BOD', 'Bodega → Bodega'), ('BOD_SUC', 'Bodega → Sucursal'), ('SUC_BOD', 'Sucursal → Bodega'), ('SUC_SUC', 'Sucursal ↔ Sucursal')], default='BOD_BOD', max_length=20),
        ),
    ]
