# Generated by Django 5.2.6 on 2025-11-27 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_transferencia_observaciones_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ubicacionbodega',
            name='almacenable',
        ),
        migrations.RemoveField(
            model_name='ubicacionbodega',
            name='pickeable',
        ),
        migrations.RemoveField(
            model_name='ubicacionsucursal',
            name='almacenable',
        ),
        migrations.RemoveField(
            model_name='ubicacionsucursal',
            name='pickeable',
        ),
        migrations.AddField(
            model_name='ubicacionbodega',
            name='area_codigo',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='ubicacionbodega',
            name='bodega_codigo',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='ubicacionbodega',
            name='estante_codigo',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='ubicacionsucursal',
            name='area_codigo',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='ubicacionsucursal',
            name='estante_codigo',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='ubicacionsucursal',
            name='sucursal_codigo',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
