# Generated by Django 5.2.7 on 2025-11-28 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_producto_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaproveedor',
            name='estado',
            field=models.CharField(choices=[('OPEN', 'Abierta'), ('PAGADA', 'Pagada'), ('ANULADA', 'Anulada')], default='OPEN', max_length=30),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='estado',
            field=models.CharField(choices=[('DRAFT', 'Borrador'), ('APROBADA', 'Aprobada'), ('CERRADA', 'Cerrada'), ('PARTIAL', 'Recepción parcial'), ('RECEIVED', 'Recepcionada'), ('CANCELLED', 'Cancelada')], default='DRAFT', max_length=30),
        ),
    ]
