# Generated by Django 5.2.6 on 2025-11-27 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_ubicacionbodega_almacenable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ubicacionbodega',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='ubicacionsucursal',
            name='nombre',
        ),
    ]
