# Generated by Django 5.2.6 on 2025-11-27 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_ubicacionbodega_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='actualizado_en',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='creado_en',
        ),
        migrations.AddField(
            model_name='producto',
            name='ubicaciones_bodega',
            field=models.ManyToManyField(blank=True, related_name='productos_bodega', to='core.ubicacionbodega'),
        ),
        migrations.AddField(
            model_name='producto',
            name='ubicaciones_sucursal',
            field=models.ManyToManyField(blank=True, related_name='productos_sucursal', to='core.ubicacionsucursal'),
        ),
    ]
