# Generated by Django 5.2.6 on 2025-11-27 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_producto_actualizado_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ubicacionbodega',
            name='bodega_codigo',
        ),
        migrations.RemoveField(
            model_name='ubicacionsucursal',
            name='sucursal_codigo',
        ),
    ]
