# Generated by Django 5.2.6 on 2025-11-27 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_ubicacionbodega_bodega_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='cantidad_validada',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Cantidad validada para movimientos desde esta ubicación.', max_digits=20),
        ),
    ]
