# Generated by Django 5.2.6 on 2025-12-02 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_facturaproveedor_estado_and_more'),
        ('core', '0009_stock_cantidad_validada'),
    ]

    operations = [
    ]
