"""
Django settings for bodega project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os

load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

SITE_URL = "http://localhost:8000"


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'bodega.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bodega.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

SUPABASE_DBNAME   = os.environ.get("SUPABASE_DBNAME", "postgres")
SUPABASE_USER     = os.environ.get("SUPABASE_USER")
SUPABASE_PASSWORD = os.environ.get("SUPABASE_PASSWORD")

# Pooler (uso normal de la app)
SUPABASE_HOST     = os.environ.get("SUPABASE_HOST")            # aws-1-us-east-2.pooler.supabase.com
SUPABASE_PORT     = os.environ.get("SUPABASE_PORT", "6543")

# Directo (migraciones)
SUPABASE_DIRECT_HOST = os.environ.get("SUPABASE_DIRECT_HOST")  # aws-1-us-east-2.supabase.com
SUPABASE_DIRECT_PORT = os.environ.get("SUPABASE_DIRECT_PORT", "5432")

DATABASES = {
    "default": {  # usa el pooler
        "ENGINE": "django.db.backends.postgresql",
        "NAME": SUPABASE_DBNAME,
        "USER": SUPABASE_USER,
        "PASSWORD": SUPABASE_PASSWORD,
        "HOST": SUPABASE_HOST,
        "PORT": SUPABASE_PORT,
        "OPTIONS": {"sslmode": "require"},
        "CONN_MAX_AGE": 0,  # evita conexiones persistentes con el pooler
    },
    "direct": {   # usa conexión directa para migraciones
        "ENGINE": "django.db.backends.postgresql",
        "NAME": SUPABASE_DBNAME,
        "USER": SUPABASE_USER,
        "PASSWORD": SUPABASE_PASSWORD,
        "HOST": SUPABASE_DIRECT_HOST,
        "PORT": SUPABASE_DIRECT_PORT,
        "OPTIONS": {"sslmode": "require"},
        "CONN_MAX_AGE": 0,
    },
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "Static"]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
